name: app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  flutter_native_splash: 2.2.4
  get_storage: 2.0.3
  font_awesome_flutter: 10.1.0
  dio: 4.0.6
  pull_to_refresh: ^2.0.0
  geocoding: 2.0.4
  cached_network_image: 3.2.1
  animate_do: 2.1.0
  geolocator: 9.0.1
  getwidget: 3.0.1
  flutter_inappwebview: 5.4.3+7
  webview_flutter: 3.0.4
  shared_preferences: 2.0.15
  equatable: 2.0.3
  html: 0.15.0
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.9.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - lib/assets/
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/assets/gif/
    - lib/assets/icons/
  uses-material-design: true

