name: app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  
  flutter_native_splash: 2.2.4
  get_storage: 2.0.3
  # font_awesome_flutter: 10.1.0
  dio: 4.0.6
  pull_to_refresh: ^2.0.0
  # card_swiper: 2.0.4
  # badges: 2.0.3
  geocoding: 2.0.4
  cached_network_image: 3.2.1
  animate_do: 2.1.0
  geolocator: 9.0.1
  getwidget: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.9.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true

